import logo from './logo.png';
import icon from './icons.png'
import island from './islands.png'
import trending from './trending.png'
import park from './national park.png'
import rooms from './rooms.png'
import side from './countryside.png'
import farms from './farms.png'
import pools from './pools.png'
import omg from './omg.png'
import beach from './beach.png'
import cabins from './cabins.png'
import castles from './castles.png'
import luxe from './luxe.png'
import mansions from './mansions.png'
import history from './history.png'
import lake from './lake.png'
import host from './host.png'
import icon1 from './icon1.png';
import icon2 from './icon2.png';
import icon3 from './icon3.png';
import icon4 from './icon4.png';
import icon5 from './icon5.png';
import icon6 from './icon6.png';
import icon7 from './icon7.png';
import icon8 from './icon8.png';
import icon9 from './icon9.png';
import icon10 from './icon10.png';
import icon11 from './icon11.png';
import icon12 from './icon12.png';
import icon13 from './icon13.png';
import island1 from './island1.png';
import island2 from './island2.png';
import island3 from './island3.png';
import island4 from './island4.png';
import island5 from './island5.png';
import island6 from './island6.png';
import island7 from './island7.png';
import island8 from './island8.png';
import island9 from './island9.png';
import island10 from './island10.png';
import island11 from './island11.png';
import island12 from './island12.png';
import island13 from './island13.png';
import island14 from './island14.png';
import island15 from './island15.png';
import trending1 from './trending1.png';
import trending2 from './trending2.png';
import trending3 from './trending3.png';
import trending4 from './trending4.png';
import trending5 from './trending5.png';
import trending6 from './trending6.png';
import trending7 from './trending7.png';
import trending8 from './trending8.png';
import trending9 from './trending9.png';
import trending10 from './trending10.png';
import trending11 from './trending11.png';
import trending12 from './trending12.png';
import trending13 from './trending13.png';
import trending14 from './trending14.png';
import trending15 from './trending15.png';
import park1 from './park1.png';
import park2 from './park2.png';
import park3 from './park3.png';
import park4 from './park4.png';
import park5 from './park5.png';
import park6 from './park6.png';
import park7 from './park7.png';
import park8 from './park8.png';
import park9 from './park9.png';
import park10 from './park10.png';
import park12 from './park12.png';
import park13 from './park13.png';
import park14 from './park14.png';
import park15 from './park15.png';
import park16 from './park16.png';
import park17 from './park17.png';
import rooms1 from './rooms1.png';
import rooms2 from './rooms2.png';
import rooms3 from './rooms3.png';
import rooms4 from './rooms4.png';
import rooms5 from './rooms5.png';
import rooms6 from './rooms6.png';
import rooms7 from './rooms7.png';
import rooms8 from './rooms8.png';
import rooms9 from './rooms9.png';
import rooms10 from './rooms10.png';
import rooms11 from './rooms11.png';
import rooms12 from './rooms12.png';
import rooms13 from './rooms13.png';
import rooms14 from './rooms14.png';
import rooms15 from './rooms15.png';
import rooms16 from './rooms16.png';
import rooms17 from './rooms17.png';
import side1 from './side1.png';
import side2 from './side2.png';
import side3 from './side3.png';
import side4 from './side4.png';
import side5 from './side5.png';
import side6 from './side6.png';
import side7 from './side7.png';
import side8 from './side8.png';
import side9 from './side9.png';
import side10 from './side10.png';
import side11 from './side11.png';
import side12 from './side12.png';
import side13 from './side13.png';
import side14 from './side14.png';
import side15 from './side15.png';
import farms1 from './farms1.png';
import farms2 from './farms2.png';
import farms3 from './farms3.png';
import farms4 from './farms4.png';
import farms5 from './farms5.png';
import farms6 from './farms6.png';
import farms7 from './farms7.png';
import farms8 from './farms2.png';
import farms9 from './farms9.png';
import farms10 from './farms10.png';
import farms11 from './farms11.png';
import farms12 from './farms1.png';
import farms13 from './farms13.png';
import farms14 from './farms14.png';
import farms15 from './farms15.png';




 export const Assets = {
  logo,

 host

 
};

export const icons = [
  { name: "icon", image: icon },
  { name: "island", image: island },
  { name: "trending", image: trending },
  { name: "park", image: park },
  { name: "rooms", image: rooms },
  { name: "side", image: side },
  { name: "farms", image: farms },
  { name: "omg", image: omg },
  { name: "beach", image: beach },
  { name: "cabins", image: cabins },
  { name: "castles", image: castles },
  { name: "luxe", image: luxe },
  { name: "mansions", image: mansions },
  { name: "history", image: history },
  { name: "lake", image: lake },
  { name: "pools", image: pools }
];


export const images = [
  // Existing data for 'icon' category
  {
    id: 1,
    image: icon1,
    category: 'icon',
    name: "Urban Studio in Downtown",
    about: 'Hosted by Alex and Jordan',
    date: 'Available Now',
    status: 'Available',
  },
  // Additional icon entries...
  {
    id: 2,
    image: icon2,
    category: 'icon',
    name: "Modern Loft with a View",
    about: 'Hosted by Chris and Taylor',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 3,
    image: icon3,
    category: 'icon',
    name: "Cozy Urban Apartment",
    about: 'Hosted by Jamie and Pat',
    date: 'Available November',
    status: 'Available',
  },
  {
    id: 4,
    image: icon4,
    category: 'icon',
    name: "Stylish Downtown Pad",
    about: 'Hosted by Jordan and Casey',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 5,
    image: icon5,
    category: 'icon',
    name: "Elegant City Studio",
    about: 'Hosted by Morgan and Alex',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 6,
    image: icon6,
    category: 'icon',
    name: "Chic Loft in the City",
    about: 'Hosted by Riley and Avery',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 7,
    image: icon7,
    category: 'icon',
    name: "Bright Modern Space",
    about: 'Hosted by Casey and Jamie',
    date: 'Available November',
    status: 'Available',
  },
  {
    id: 8,
    image: icon8,
    category: 'icon',
    name: "Stylish Studio Apartment",
    about: 'Hosted by Quinn and Taylor',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 9,
    image: icon9,
    category: 'icon',
    name: "Luxury Urban Loft",
    about: 'Hosted by Jordan and Morgan',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 10,
    image: icon10,
    category: 'icon',
    name: "Contemporary City Retreat",
    about: 'Hosted by Pat and Riley',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 11,
    image: icon11,
    category: 'icon',
    name: "Modern Downtown Loft",
    about: 'Hosted by Avery and Chris',
    date: 'Available November',
    status: 'Available',
  },
  {
    id: 12,
    image: icon12,
    category: 'icon',
    name: "Sleek City Apartment",
    about: 'Hosted by Jamie and Quinn',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 13,
    image: icon13,
    category: 'icon',
    name: "Urban Chic Studio",
    about: 'Hosted by Taylor and Alex',
    date: 'Available Now',
    status: 'Available',
  },
  // New island data
  {
    id: 14,
    image: island1,
    category: 'island',
    name: "Private Island Retreat",
    about: 'Hosted by John and Emily',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 15,
    image: island2,
    category: 'island',
    name: "Secluded Tropical Paradise",
    about: 'Hosted by David and Sarah',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 16,
    image: island3,
    category: 'island',
    name: "Exclusive Island Getaway",
    about: 'Hosted by Olivia and Liam',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 17,
    image: island4,
    category: 'island',
    name: "Luxury Island Villa",
    about: 'Hosted by Isabella and Ethan',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 18,
    image: island5,
    category: 'island',
    name: "Tropical Island Haven",
    about: 'Hosted by Emma and Noah',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 19,
    image: island6,
    category: 'island',
    name: "Relaxing Island Escape",
    about: 'Hosted by Sophia and James',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 20,
    image: island7,
    category: 'island',
    name: "Serene Island Retreat",
    about: 'Hosted by Mia and Mason',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 21,
    image: island8,
    category: 'island',
    name: "Hidden Island Oasis",
    about: 'Hosted by Harper and Benjamin',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 22,
    image: island9,
    category: 'island',
    name: "Unspoiled Island Sanctuary",
    about: 'Hosted by Ava and Logan',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 23,
    image: island10,
    category: 'island',
    name: "Sunny Island Getaway",
    about: 'Hosted by Amelia and Lucas',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 24,
    image: island11,
    category: 'island',
    name: "Tropical Private Island",
    about: 'Hosted by Evelyn and Henry',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 25,
    image: island12,
    category: 'island',
    name: "Island Hideaway",
    about: 'Hosted by Abigail and Owen',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 26,
    image: island13,
    category: 'island',
    name: "Scenic Island Retreat",
    about: 'Hosted by Scarlett and Jack',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 27,
    image: island14,
    category: 'island',
    name: "Remote Island Paradise",
    about: 'Hosted by Ella and Aiden',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 28,
    image: island15,
    category: 'island',
    name: "Exclusive Island Resort",
    about: 'Hosted by Grace and Alexander',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 29,
    image: trending1,
    category: 'trending',
    name: "Trendy Urban Loft",
    about: 'Hosted by Olivia and Ethan',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 30,
    image: trending2,
    category: 'trending',
    name: "Modern Trendsetting Apartment",
    about: 'Hosted by Sophia and Liam',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 31,
    image: trending3,
    category: 'trending',
    name: "Stylish Trendy Loft",
    about: 'Hosted by Emma and Noah',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 32,
    image: trending4,
    category: 'trending',
    name: "Trendy Downtown Studio",
    about: 'Hosted by Mia and Mason',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 33,
    image: trending5,
    category: 'trending',
    name: "Luxurious Trendy Pad",
    about: 'Hosted by Harper and Lucas',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 34,
    image: trending6,
    category: 'trending',
    name: "Trendy City Hideaway",
    about: 'Hosted by Ava and James',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 35,
    image: trending7,
    category: 'trending',
    name: "Popular Trendy Loft",
    about: 'Hosted by Isabella and Henry',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 36,
    image: trending8,
    category: 'trending',
    name: "Sleek Trendy Studio",
    about: 'Hosted by Abigail and Alexander',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 37,
    image: trending9,
    category: 'trending',
    name: "Trendy Penthouse Suite",
    about: 'Hosted by Grace and Owen',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 38,
    image: trending10,
    category: 'trending',
    name: "Trendy Urban Oasis",
    about: 'Hosted by Ella and Jack',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 39,
    image: trending11,
    category: 'trending',
    name: "Trendy Modern Apartment",
    about: 'Hosted by Scarlett and Aiden',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 40,
    image: trending12,
    category: 'trending',
    name: "Trendy Downtown Penthouse",
    about: 'Hosted by Amelia and Logan',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 41,
    image: trending13,
    category: 'trending',
    name: "Trendy Loft in the Heart of the City",
    about: 'Hosted by Olivia and Ethan',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 42,
    image: trending14,
    category: 'trending',
    name: "Trendy Chic Apartment",
    about: 'Hosted by Sophia and Liam',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 43,
    image: trending15,
    category: 'trending',
    name: "Trendy Urban Escape",
    about: 'Hosted by Emma and Noah',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 44,
    image: park1,
    category: 'park',
    name: "Cozy Cabin Near National Park",
    about: 'Hosted by Olivia and Ethan',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 45,
    image: park2,
    category: 'park',
    name: "Mountain View Cottage",
    about: 'Hosted by Sophia and Liam',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 46,
    image: park3,
    category: 'park',
    name: "Rustic Parkside Retreat",
    about: 'Hosted by Emma and Noah',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 47,
    image: park4,
    category: 'park',
    name: "Lakeside Cabin in National Park",
    about: 'Hosted by Mia and Mason',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 48,
    image: park5,
    category: 'park',
    name: "Countryside Cottage Near Park",
    about: 'Hosted by Harper and Lucas',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 49,
    image: park6,
    category: 'park',
    name: "Forest Lodge Near National Park",
    about: 'Hosted by Ava and James',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 50,
    image: park7,
    category: 'park',
    name: "Parkside Wilderness Escape",
    about: 'Hosted by Isabella and Henry',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 51,
    image: park8,
    category: 'park',
    name: "Secluded National Park Cabin",
    about: 'Hosted by Abigail and Alexander',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 52,
    image: park9,
    category: 'park',
    name: "Quiet Retreat Near National Park",
    about: 'Hosted by Grace and Owen',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 53,
    image: park10,
    category: 'park',
    name: "Peaceful Parkside Cabin",
    about: 'Hosted by Ella and Jack',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 54,
    image:park1,
    category: 'park',
    name: "Charming Cottage Near National Park",
    about: 'Hosted by Scarlett and Aiden',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 55,
    image: park12,
    category: 'park',
    name: "Woodland Cabin by National Park",
    about: 'Hosted by Amelia and Logan',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 56,
    image: park13,
    category: 'park',
    name: "Parkview Mountain Chalet",
    about: 'Hosted by Olivia and Ethan',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 57,
    image: park14,
    category: 'park',
    name: "Riverside Cabin in National Park",
    about: 'Hosted by Sophia and Liam',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 58,
    image: park15,
    category: 'park',
    name: "Hilltop Park Cabin",
    about: 'Hosted by Emma and Noah',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 59,
    image: park16,
    category: 'park',
    name: "Parkside Adventure Cabin",
    about: 'Hosted by William and Charlotte',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 60,
    image: park17,
    category: 'park',
    name: "Rustic Escape by the National Park",
    about: 'Hosted by Emily and Benjamin',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 61,
    image: rooms1,
    category: 'rooms',
    name: "Modern Room with a View",
    about: 'Hosted by Daniel and Ava',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 62,
    image: rooms2,
    category: 'rooms',
    name: "Cozy Room in the City Center",
    about: 'Hosted by Lucas and Emma',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 63,
    image: rooms3,
    category: 'rooms',
    name: "Elegant Room with Balcony",
    about: 'Hosted by Sophia and James',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 64,
    image: rooms4,
    category: 'rooms',
    name: "Spacious Room Near the Beach",
    about: 'Hosted by Liam and Isabella',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 65,
    image: rooms5,
    category: 'rooms',
    name: "Bright Room with Garden Access",
    about: 'Hosted by Charlotte and Mason',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 66,
    image: rooms6,
    category: 'rooms',
    name: "Charming Room in a Historic Building",
    about: 'Hosted by Oliver and Mia',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 67,
    image: rooms7,
    category: 'rooms',
    name: "Luxury Room with City Views",
    about: 'Hosted by Amelia and Ethan',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 68,
    image: rooms8,
    category: 'rooms',
    name: "Room in a Stylish Downtown Apartment",
    about: 'Hosted by Harper and Jack',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 69,
    image: rooms9,
    category: 'rooms',
    name: "Cozy Attic Room",
    about: 'Hosted by Elijah and Grace',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 70,
    image: rooms10,
    category: 'rooms',
    name: "Serene Room in the Countryside",
    about: 'Hosted by William and Olivia',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 71,
    image: rooms11,
    category: 'rooms',
    name: "Quiet Room with Private Bath",
    about: 'Hosted by Emily and Henry',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 72,
    image: rooms12,
    category: 'rooms',
    name: "Spacious Room in a Shared House",
    about: 'Hosted by Lily and Alexander',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 73,
    image: rooms13,
    category: 'rooms',
    name: "Luxurious Room with Pool Access",
    about: 'Hosted by Chloe and Sebastian',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 74,
    image: rooms14,
    category: 'rooms',
    name: "Room in a Charming Villa",
    about: 'Hosted by Hannah and Benjamin',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 75,
    image: rooms15,
    category: 'rooms',
    name: "Comfortable Room in the City",
    about: 'Hosted by Avery and Daniel',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 76,
    image: rooms16,
    category: 'rooms',
    name: "Classic Room with Modern Amenities",
    about: 'Hosted by Zoey and Jackson',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 77,
    image: rooms17,
    category: 'rooms',
    name: "Elegant Room in a Boutique Hotel",
    about: 'Hosted by Layla and Carter',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 78,
    image: side1,
    category: 'side',
    name: "Countryside Cottage Getaway",
    about: 'Hosted by Amelia and Noah',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 79,
    image: side2,
    category: 'side',
    name: "Riverside Retreat in the Country",
    about: 'Hosted by Isabella and Ethan',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 80,
    image: side3,
    category: 'side',
    name: "Country House with a View",
    about: 'Hosted by Sophia and Liam',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 81,
    image: side4,
    category: 'side',
    name: "Farmhouse by the Lake",
    about: 'Hosted by Olivia and Mason',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 82,
    image: side5,
    category: 'side',
    name: "Rustic Countryside Cottage",
    about: 'Hosted by Mia and Lucas',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 83,
    image: side6,
    category: 'side',
    name: "Peaceful Farmhouse in the Hills",
    about: 'Hosted by Ava and James',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 84,
    image: side7,
    category: 'side',
    name: "Country Home with Gardens",
    about: 'Hosted by Harper and Jackson',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 85,
    image: side8,
    category: 'side',
    name: "Charming House in the Countryside",
    about: 'Hosted by Charlotte and Elijah',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 86,
    image: side9,
    category: 'side',
    name: "Country Villa with Large Yard",
    about: 'Hosted by Ella and Alexander',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 87,
    image: side10,
    category: 'side',
    name: "Quiet Escape in the Country",
    about: 'Hosted by Emily and Oliver',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 88,
    image: side11,
    category: 'side',
    name: "Secluded House Near the Forest",
    about: 'Hosted by Scarlett and Henry',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 89,
    image: side12,
    category: 'side',
    name: "Cottage with Vineyard Views",
    about: 'Hosted by Grace and Sebastian',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 90,
    image: side13,
    category: 'side',
    name: "Country House with Pool",
    about: 'Hosted by Chloe and William',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 91,
    image: side14,
    category: 'side',
    name: "Traditional Countryside Cottage",
    about: 'Hosted by Layla and Lucas',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 92,
    image: side15,
    category: 'side',
    name: "Quiet Hillside House",
    about: 'Hosted by Hannah and Jack',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 93,
    image: farms1,
    category: 'farms',
    name: "Organic Farm Stay",
    about: 'Hosted by Olivia and Benjamin',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 94,
    image: farms2,
    category: 'farms',
    name: "Farmhouse Retreat with Animals",
    about: 'Hosted by Charlotte and Ethan',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 95,
    image: farms3,
    category: 'farms',
    name: "Eco-Friendly Farm Experience",
    about: 'Hosted by Isabella and Lucas',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 96,
    image: farms4,
    category: 'farms',
    name: "Farm Stay with Vineyard Views",
    about: 'Hosted by Mia and Jack',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 97,
    image: farms5,
    category: 'farms',
    name: "Rustic Farmhouse with Barn",
    about: 'Hosted by Amelia and Henry',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 98,
    image: farms6,
    category: 'farms',
    name: "Luxury Farm Stay",
    about: 'Hosted by Harper and William',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 99,
    image: farms7,
    category: 'farms',
    name: "Charming Farm Cottage",
    about: 'Hosted by Sophia and Alexander',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 100,
    image: farms8,
    category: 'farms',
    name: "Secluded Farmhouse with Views",
    about: 'Hosted by Ella and James',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 101,
    image: farms9,
    category: 'farms',
    name: "Quaint Farmhouse by the River",
    about: 'Hosted by Emily and Noah',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 102,
    image: farms10,
    category: 'farms',
    name: "Farm Stay with Fresh Produce",
    about: 'Hosted by Grace and Liam',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 103,
    image: farms11,
    category: 'farms',
    name: "Historic Farmhouse",
    about: 'Hosted by Chloe and Elijah',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 104,
    image: farms12,
    category: 'farms',
    name: "Scenic Farm Stay",
    about: 'Hosted by Layla and Mason',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 105,
    image: farms13,
    category: 'farms',
    name: "Family-Friendly Farm Retreat",
    about: 'Hosted by Hannah and Oliver',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 106,
    image: farms14,
    category: 'farms',
    name: "Quiet Farm Stay with Gardens",
    about: 'Hosted by Zoey and Carter',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 107,
    image: farms15,
    category: 'farms',
    name: "Tranquil Farm Cottage",
    about: 'Hosted by Scarlett and Daniel',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 108,
    image: icon1,
    category: 'omg',
    name: "Unbelievable City Loft",
    about: 'Hosted by Sophia and Daniel',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 109,
    image: island2,
    category: 'omg',
    name: "Island View Penthouse",
    about: 'Hosted by Ella and Liam',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 110,
    image: trending3,
    category: 'omg',
    name: "Trendy Downtown Studio",
    about: 'Hosted by Noah and Emily',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 111,
    image: park4,
    category: 'omg',
    name: "Loft Near National Park",
    about: 'Hosted by Mia and Ethan',
    date: 'Available December',
    status: 'Available',
  },
  {
    id: 112,
    image: rooms5,
    category: 'omg',
    name: "City Lights High-Rise",
    about: 'Hosted by Amelia and Lucas',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 113,
    image: side6,
    category: 'omg',
    name: "OMG Mansion in Countryside",
    about: 'Hosted by Emma and Oliver',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 114,
    image: farms7,
    category: 'omg',
    name: "Unique Farmhouse Retreat",
    about: 'Hosted by Olivia and Benjamin',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 115,
    image: side8,
    category: 'omg',
    name: "OMG Cottage in the Hills",
    about: 'Hosted by Isabella and William',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 116,
    image: island9,
    category: 'omg',
    name: "Incredible Island Villa",
    about: 'Hosted by Harper and James',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 117,
    image: park10,
    category: 'omg',
    name: "Luxury Stay Near the Park",
    about: 'Hosted by Ava and Jack',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 118,
    image: rooms11,
    category: 'omg',
    name: "City View Loft with Pool",
    about: 'Hosted by Layla and Mason',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 119,
    image: side12,
    category: 'omg',
    name: "Stunning Countryside Retreat",
    about: 'Hosted by Grace and Henry',
    date: 'Available Now',
    status: 'Booked',
  },
  {
    id: 120,
    image: trending13,
    category: 'omg',
    name: "City Penthouse with Terrace",
    about: 'Hosted by Scarlett and Oliver',
    date: 'Available December',
    status: 'Available',
  },
  {
    id: 121,
    image: farms14,
    category: 'omg',
    name: "OMFG Rural Villa",
    about: 'Hosted by Hannah and Noah',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 122,
    image: icon13,
    category: 'omg',
    name: "Spectacular OMG Penthouse",
    about: 'Hosted by Charlotte and Jackson',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 123,
    image: icon12,
    category: 'beach',
    name: "Sunny Beachfront Villa",
    about: 'Hosted by Daniel and Olivia',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 124,
    image: icon2,
    category: 'beach',
    name: "Tropical Beach House",
    about: 'Hosted by Mia and Noah',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 125,
    image: trending7,
    category: 'beach',
    name: "Oceanfront Bungalow",
    about: 'Hosted by Sophia and Lucas',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 126,
    image: island4,
    category: 'beach',
    name: "Luxurious Beach Retreat",
    about: 'Hosted by Emily and Mason',
    date: 'Available December',
    status: 'Available',
  },
  {
    id: 127,
    image: side10,
    category: 'beach',
    name: "Cozy Beach Cottage",
    about: 'Hosted by Harper and James',
    date: 'Available Now',
    status: 'Booked',
  },
  {
    id: 128,
    image: farms11,
    category: 'beach',
    name: "Seaside Resort Room",
    about: 'Hosted by Isabella and Oliver',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 129,
    image: park6,
    category: 'beach',
    name: "Charming Beach House",
    about: 'Hosted by Ava and Henry',
    date: 'Available November',
    status: 'Available',
  },
  {
    id: 130,
    image: icon13,
    category: 'beach',
    name: "Private Beachfront Escape",
    about: 'Hosted by Chloe and Ethan',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 131,
    image: rooms8,
    category: 'beach',
    name: "Beachside Luxury Suite",
    about: 'Hosted by Grace and Liam',
    date: 'Available Now',
    status: 'Pending',
  },
  {
    id: 132,
    image: icon2,
    category: 'beach',
    name: "Sunny Beach House",
    about: 'Hosted by Zoey and Daniel',
    date: 'Available October',
    status: 'Available',
  },
  {
    id: 133,
    image: trending7,
    category: 'beach',
    name: "Relaxing Beachfront Retreat",
    about: 'Hosted by Scarlett and Noah',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 134,
    image: farms10,
    category: 'beach',
    name: "Modern Beach Villa",
    about: 'Hosted by Layla and Jackson',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 135,
    image: side10,
    category: 'beach',
    name: "Chic Oceanview Apartment",
    about: 'Hosted by Hannah and Carter',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 136,
    image: farms11,
    category: 'beach',
    name: "Elegant Beach House",
    about: 'Hosted by Emily and Sebastian',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 137,
    image: park6,
    category: 'beach',
    name: "Sunny Oceanfront Condo",
    about: 'Hosted by Lily and Benjamin',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 138,
    image: icon2,
    category: 'cabins',
    name: "Cozy Mountain Cabin",
    about: 'Hosted by Daniel and Olivia',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 139,
    image: island4,
    category: 'cabins',
    name: "Rustic Log Cabin",
    about: 'Hosted by Mia and Noah',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 140,
    image: trending7,
    category: 'cabins',
    name: "Modern Cabin Retreat",
    about: 'Hosted by Sophia and Lucas',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 141,
    image: icon3,
    category: 'cabins',
    name: "Luxury Cabin with Hot Tub",
    about: 'Hosted by Emily and Mason',
    date: 'Available December',
    status: 'Available',
  },
  {
    id: 142,
    image: side10,
    category: 'cabins',
    name: "Charming Cabin in the Woods",
    about: 'Hosted by Harper and James',
    date: 'Available Now',
    status: 'Booked',
  },
  {
    id: 143,
    image: farms11,
    category: 'cabins',
    name: "Secluded Forest Cabin",
    about: 'Hosted by Isabella and Oliver',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 144,
    image: park6,
    category: 'cabins',
    name: "Historic Cabin Retreat",
    about: 'Hosted by Ava and Henry',
    date: 'Available November',
    status: 'Available',
  },
  {
    id: 145,
    image: icon2,
    category: 'cabins',
    name: "Quaint Cabin with Lake View",
    about: 'Hosted by Chloe and Ethan',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 146,
    image: island4,
    category: 'cabins',
    name: "Spacious Mountain Lodge",
    about: 'Hosted by Grace and Liam',
    date: 'Available Now',
    status: 'Pending',
  },
  {
    id: 147,
    image: trending7,
    category: 'cabins',
    name: "Elegant Alpine Cabin",
    about: 'Hosted by Zoey and Daniel',
    date: 'Available October',
    status: 'Available',
  },
  {
    id: 148,
    image: farms10,
    category: 'cabins',
    name: "Secluded Cabin Escape",
    about: 'Hosted by Scarlett and Noah',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 149,
    image: side10,
    category: 'cabins',
    name: "Luxury Woodland Cabin",
    about: 'Hosted by Layla and Jackson',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 150,
    image: farms11,
    category: 'cabins',
    name: "Chic Modern Cabin",
    about: 'Hosted by Hannah and Carter',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 151,
    image: park6,
    category: 'cabins',
    name: "Cozy Cabin with Fireplace",
    about: 'Hosted by Emily and Sebastian',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 152,
    image: icon2,
    category: 'cabins',
    name: "Sunny Mountain Cabin",
    about: 'Hosted by Lily and Benjamin',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 153,
    image: icon2,
    category: 'castles',
    name: "Grand Medieval Castle",
    about: 'Hosted by Arthur and Elaine',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 154,
    image: island4,
    category: 'castles',
    name: "Royal Castle with Garden",
    about: 'Hosted by Richard and Eleanor',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 155,
    image: trending7,
    category: 'castles',
    name: "Enchanting Castle Retreat",
    about: 'Hosted by Elizabeth and Henry',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 156,
    image: farms15,
    category: 'castles',
    name: "Historic Castle Fortress",
    about: 'Hosted by Margaret and Edward',
    date: 'Available December',
    status: 'Available',
  },
  {
    id: 157,
    image: side10,
    category: 'castles',
    name: "Castle with Tower View",
    about: 'Hosted by Victoria and William',
    date: 'Available Now',
    status: 'Booked',
  },
  {
    id: 158,
    image: farms11,
    category: 'castles',
    name: "Medieval Castle Estate",
    about: 'Hosted by Alice and George',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 159,
    image: park6,
    category: 'castles',
    name: "Luxurious Castle Residence",
    about: 'Hosted by Charlotte and James',
    date: 'Available November',
    status: 'Available',
  },
  {
    id: 160,
    image: icon2,
    category: 'castles',
    name: "Castle with Courtyard",
    about: 'Hosted by James and Anna',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 161,
    image: island4,
    category: 'castles',
    name: "Fantasy Castle Adventure",
    about: 'Hosted by Samuel and Lucy',
    date: 'Available Now',
    status: 'Pending',
  },
  {
    id: 162,
    image: trending7,
    category: 'castles',
    name: "Imposing Castle Fortress",
    about: 'Hosted by Emma and Thomas',
    date: 'Available October',
    status: 'Available',
  },
  {
    id: 163,
    image: island5,
    category: 'castles',
    name: "Castle with Historical Charm",
    about: 'Hosted by Robert and Claire',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 164,
    image: side10,
    category: 'castles',
    name: "Castle with Grand Hall",
    about: 'Hosted by Laura and Michael',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 165,
    image: farms11,
    category: 'castles',
    name: "Castle with Scenic Views",
    about: 'Hosted by Olivia and Daniel',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 166,
    image: park6,
    category: 'castles',
    name: "Charming Castle Getaway",
    about: 'Hosted by Amelia and Matthew',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 167,
    image: icon2,
    category: 'castles',
    name: "Regal Castle Stay",
    about: 'Hosted by Sophia and Alexander',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 168,
    image: rooms9,
    category: 'luxe',
    name: "Luxury Penthouse in the City",
    about: 'Hosted by Daniel and Olivia',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 169,
    image: island5,
    category: 'luxe',
    name: "Exclusive Island Retreat",
    about: 'Hosted by Mia and Jack',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 170,
    image: trending8,
    category: 'luxe',
    name: "Trendy Luxe Loft",
    about: 'Hosted by Sophia and Liam',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 171,
    image: side11,
    category: 'luxe',
    name: "Elegant Countryside Mansion",
    about: 'Hosted by Ava and Noah',
    date: 'Available December',
    status: 'Available',
  },
  {
    id: 172,
    image: farms12,
    category: 'luxe',
    name: "Opulent Farmhouse Retreat",
    about: 'Hosted by Mia and Lucas',
    date: 'Available Now',
    status: 'Booked',
  },
  {
    id: 173,
    image: park7,
    category: 'luxe',
    name: "Grand Parkside Estate",
    about: 'Hosted by Emma and James',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 174,
    image: side11,
    category: 'luxe',
    name: "Modern Luxury Residence",
    about: 'Hosted by Olivia and Alexander',
    date: 'Available November',
    status: 'Available',
  },
  {
    id: 175,
    image: farms12,
    category: 'luxe',
    name: "Luxury Farm Estate",
    about: 'Hosted by Sophia and Ethan',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 176,
    image: island5,
    category: 'luxe',
    name: "Island Paradise Villa",
    about: 'Hosted by Charlotte and Benjamin',
    date: 'Available Now',
    status: 'Pending',
  },
  {
    id: 177,
    image: trending8,
    category: 'luxe',
    name: "Exclusive Trendy Loft",
    about: 'Hosted by Isabella and Jack',
    date: 'Available October',
    status: 'Available',
  },
  {
    id: 178,
    image: side11,
    category: 'luxe',
    name: "Sleek Countryside Retreat",
    about: 'Hosted by Ella and Mason',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 179,
    image: park7,
    category: 'luxe',
    name: "Chic Parkside Mansion",
    about: 'Hosted by Ava and William',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 180,
    image: farms12,
    category: 'luxe',
    name: "Upscale Farmhouse",
    about: 'Hosted by Mia and Oliver',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 181,
    image: island5,
    category: 'luxe',
    name: "Luxurious Island Retreat",
    about: 'Hosted by Harper and Noah',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 182,
    image: rooms9,
    category: 'luxe',
    name: "Grand Luxe Villa",
    about: 'Hosted by Sophia and Lucas',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 183,
    image: rooms8,
    category: 'mansions',
    name: "Opulent Mansion in the City",
    about: 'Hosted by Jacob and Olivia',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 184,
    image: island4,
    category: 'mansions',
    name: "Grand Island Estate",
    about: 'Hosted by Daniel and Mia',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 185,
    image: trending7,
    category: 'mansions',
    name: "Luxurious Urban Mansion",
    about: 'Hosted by James and Ella',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 186,
    image: side10,
    category: 'mansions',
    name: "Elegant Country Mansion",
    about: 'Hosted by Lucas and Ava',
    date: 'Available December',
    status: 'Available',
  },
  {
    id: 187,
    image: farms11,
    category: 'mansions',
    name: "Exclusive Farm Mansion",
    about: 'Hosted by Grace and Noah',
    date: 'Available Now',
    status: 'Booked',
  },
  {
    id: 188,
    image: park6,
    category: 'mansions',
    name: "Grand Parkside Mansion",
    about: 'Hosted by Lily and Ethan',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 189,
    image: side10,
    category: 'mansions',
    name: "Regal Country Estate",
    about: 'Hosted by Emma and Oliver',
    date: 'Available November',
    status: 'Available',
  },
  {
    id: 190,
    image: farms11,
    category: 'mansions',
    name: "Elegant Farmhouse Mansion",
    about: 'Hosted by Isabella and Benjamin',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 191,
    image: island4,
    category: 'mansions',
    name: "Prestigious Island Mansion",
    about: 'Hosted by Amelia and Mason',
    date: 'Available Now',
    status: 'Pending',
  },
  {
    id: 192,
    image: trending7,
    category: 'mansions',
    name: "Modern High-Rise Mansion",
    about: 'Hosted by Sophia and Jack',
    date: 'Available October',
    status: 'Available',
  },
  {
    id: 193,
    image: side10,
    category: 'mansions',
    name: "Sophisticated Country Mansion",
    about: 'Hosted by Ella and Lucas',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 194,
    image: park6,
    category: 'mansions',
    name: "Stylish Parkside Mansion",
    about: 'Hosted by Mia and Alexander',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 195,
    image: farms11,
    category: 'mansions',
    name: "Luxurious Mountain Mansion",
    about: 'Hosted by Ava and Michael',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 196,
    image: island4,
    category: 'mansions',
    name: "Exquisite Island Residence",
    about: 'Hosted by Harper and William',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 197,
    image: rooms8,
    category: 'mansions',
    name: "Glamorous Castle Mansion",
    about: 'Hosted by Ella and Noah',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 198,
    image: icon1,
    category: 'history',
    name: "Historic Urban Loft",
    about: 'Hosted by Daniel and Mia',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 199,
    image: island5,
    category: 'history',
    name: "Vintage Island Retreat",
    about: 'Hosted by Sophia and Liam',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 200,
    image: trending9,
    category: 'history',
    name: "Retro Trendy Loft",
    about: 'Hosted by Ava and Noah',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 201,
    image: park2,
    category: 'history',
    name: "Classic Parkside Estate",
    about: 'Hosted by Mia and Lucas',
    date: 'Available December',
    status: 'Available',
  },
  {
    id: 202,
    image: rooms7,
    category: 'history',
    name: "Traditional Countryside House",
    about: 'Hosted by Olivia and Ryan',
    date: 'Available Now',
    status: 'Booked',
  },
  {
    id: 203,
    image: side12,
    category: 'history',
    name: "Historic Farmhouse Retreat",
    about: 'Hosted by Emma and James',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 204,
    image: farms6,
    category: 'history',
    name: "Elegant Historical Residence",
    about: 'Hosted by Charlotte and Benjamin',
    date: 'Available November',
    status: 'Available',
  },
  {
    id: 205,
    image: icon1,
    category: 'history',
    name: "Charming Island Cottage",
    about: 'Hosted by Sophia and Ethan',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 206,
    image: island5,
    category: 'history',
    name: "Quaint Trendy Loft",
    about: 'Hosted by Isabella and Jack',
    date: 'Available Now',
    status: 'Pending',
  },
  {
    id: 207,
    image: trending9,
    category: 'history',
    name: "Vintage Parkside Mansion",
    about: 'Hosted by Ella and Mason',
    date: 'Available October',
    status: 'Available',
  },
  {
    id: 208,
    image: park2,
    category: 'history',
    name: "Classic Countryside Retreat",
    about: 'Hosted by Mia and William',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 209,
    image: rooms7,
    category: 'history',
    name: "Historic Farm Estate",
    about: 'Hosted by Ava and Oliver',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 210,
    image: side12,
    category: 'history',
    name: "Old-World Urban Loft",
    about: 'Hosted by Daniel and Harper',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 211,
    image: farms6,
    category: 'history',
    name: "Classic Island Retreat",
    about: 'Hosted by Mia and Noah',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 212,
    image: icon1,
    category: 'history',
    name: "Retro Trendy Apartment",
    about: 'Hosted by Sophia and Lucas',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 213,
    image: rooms5,
    category: 'lake',
    name: "Lakeside Luxury Villa",
    about: 'Hosted by James and Emma',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 214,
    image: island2,
    category: 'lake',
    name: "Serene Lakefront Estate",
    about: 'Hosted by Olivia and Daniel',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 215,
    image: trending3,
    category: 'lake',
    name: "Modern Lakehouse Retreat",
    about: 'Hosted by Jacob and Ava',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 216,
    image: side6,
    category: 'lake',
    name: "Charming Lakeside Cottage",
    about: 'Hosted by Mia and Lucas',
    date: 'Available December',
    status: 'Available',
  },
  {
    id: 217,
    image: farms7,
    category: 'lake',
    name: "Rustic Lake Farmhouse",
    about: 'Hosted by Noah and Sophia',
    date: 'Available Now',
    status: 'Booked',
  },
  {
    id: 218,
    image: park4,
    category: 'lake',
    name: "Elegant Lakeside Mansion",
    about: 'Hosted by Grace and Ethan',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 219,
    image: side6,
    category: 'lake',
    name: "Stylish Lakehouse Estate",
    about: 'Hosted by Ella and Oliver',
    date: 'Available November',
    status: 'Available',
  },
  {
    id: 220,
    image: farms7,
    category: 'lake',
    name: "Luxury Lake Farm Retreat",
    about: 'Hosted by Isabella and Benjamin',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 221,
    image: island2,
    category: 'lake',
    name: "Exclusive Lake Island Home",
    about: 'Hosted by Amelia and Mason',
    date: 'Available Now',
    status: 'Pending',
  },
  {
    id: 222,
    image: trending3,
    category: 'lake',
    name: "Grand Lakeview Villa",
    about: 'Hosted by Sophia and Jack',
    date: 'Available October',
    status: 'Available',
  },
  {
    id: 223,
    image: side6,
    category: 'lake',
    name: "Historic Lake Mansion",
    about: 'Hosted by Ella and Noah',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 224,
    image: park4,
    category: 'lake',
    name: "Classic Lakeside Villa",
    about: 'Hosted by Mia and Alexander',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 225,
    image: farms7,
    category: 'lake',
    name: "Luxurious Lakeside Farmhouse",
    about: 'Hosted by Ava and Michael',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 226,
    image: island2,
    category: 'lake',
    name: "Chic Lake Island Retreat",
    about: 'Hosted by Harper and William',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 227,
    image: rooms5,
    category: 'lake',
    name: "Elegant Lake House",
    about: 'Hosted by Ella and Noah',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 213,
    image: icon3,
    category: 'pools',
    name: "Modern Poolside Retreat",
    about: 'Hosted by Alice and Bob',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 214,
    image: island8,
    category: 'pools',
    name: "Island Pool Paradise",
    about: 'Hosted by Eva and George',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 215,
    image: trending6,
    category: 'pools',
    name: "Trendy Poolside Loft",
    about: 'Hosted by Mia and John',
    date: 'Available November',
    status: 'Pending',
  },
  {
    id: 216,
    image: park4,
    category: 'pools',
    name: "Parkside Pool Villa",
    about: 'Hosted by Claire and David',
    date: 'Available December',
    status: 'Available',
  },
  {
    id: 217,
    image: rooms5,
    category: 'pools',
    name: "Spacious Poolside Apartment",
    about: 'Hosted by Lucy and Daniel',
    date: 'Available Now',
    status: 'Booked',
  },
  {
    id: 218,
    image: side7,
    category: 'pools',
    name: "Countryside Pool Retreat",
    about: 'Hosted by Emma and Oliver',
    date: 'Available October',
    status: 'Pending',
  },
  {
    id: 219,
    image: farms3,
    category: 'pools',
    name: "Farmhouse Pool Experience",
    about: 'Hosted by Anna and Jacob',
    date: 'Available November',
    status: 'Available',
  },
  {
    id: 220,
    image: icon3,
    category: 'pools',
    name: "Luxury Poolside Estate",
    about: 'Hosted by James and Isabella',
    date: 'Available December',
    status: 'Booked',
  },
  {
    id: 221,
    image: island8,
    category: 'pools',
    name: "Tropical Pool Retreat",
    about: 'Hosted by Olivia and Jack',
    date: 'Available Now',
    status: 'Pending',
  },
  {
    id: 222,
    image: trending6,
    category: 'pools',
    name: "Modern Poolside Loft",
    about: 'Hosted by Sophia and Liam',
    date: 'Available October',
    status: 'Available',
  },
  {
    id: 223,
    image: park4,
    category: 'pools',
    name: "Elegant Pool Villa",
    about: 'Hosted by Ava and Noah',
    date: 'Available November',
    status: 'Booked',
  },
  {
    id: 224,
    image: rooms5,
    category: 'pools',
    name: "Stylish Poolside Apartment",
    about: 'Hosted by Mia and Liam',
    date: 'Available December',
    status: 'Pending',
  },
  {
    id: 225,
    image: side7,
    category: 'pools',
    name: "Charming Poolside Retreat",
    about: 'Hosted by Ella and Mason',
    date: 'Available Now',
    status: 'Available',
  },
  {
    id: 226,
    image: farms3,
    category: 'pools',
    name: "Rustic Poolside Experience",
    about: 'Hosted by Daniel and Ava',
    date: 'Available October',
    status: 'Booked',
  },
  {
    id: 227,
    image: icon3,
    category: 'pools',
    name: "Elegant Poolside Mansion",
    about: 'Hosted by Sophie and James',
    date: 'Available November',
    status: 'Pending',
  },
];

